sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x32"
  - sleep 3 # give xvfb some time to start