name: Build and release FXGL dialogue editor

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache maven deps
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Install FXGL
      run: mvn -T 4 install -pl :fxgl -am `-DskipTests=true `-Dgpg.skip=true `-Dlicense.skip=true `-Dpmd.skip=true
    - name: Build FXGL dialogue editor for Windows
      run: |
        cd fxgl-tools
        mvn compile
        mvn javafx:jlink
    - name: Upload FXGL dialogue editor
      env:
        UP_USER_EMAIL: ${{ secrets.UP_USER_EMAIL }}
        UP_GH_TOKEN: ${{ secrets.UP_GH_TOKEN }}
      run: |
        echo "Creating upload dir"
        mkdir upload
        cd upload
        git clone --quiet https://github.com/AlmasB/builds
        cd builds
        git config user.email "$env:UP_USER_EMAIL"
        git config user.name "up-server"
        cp ../../fxgl-tools/target/fxgl-dialogue-editor.zip fxgl/
        git add fxgl/
        git commit -m "upload-build.sh"
        git push --quiet https://"$env:UP_GH_TOKEN"@github.com/AlmasB/builds.git master
        echo "Uploaded build"