name: Build and release FXGL dialogue editor

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install FXGL
      run: mvn -T 4 install -pl :fxgl -am `-DskipTests=true `-Dgpg.skip=true `-Dlicense.skip=true `-Dpmd.skip=true
    - name: Build FXGL dialogue editor for Windows
      run: |
        cd fxgl-tools
        mvn javafx:jlink
    - name: Upload FXGL dialogue editor to 11.9
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/AlmasB/FXGL/releases/11.9/assets
        asset_path: ./target/fxgl-dialogue-editor.zip
        asset_name: fxgl-dialogue-editor-0.2-win.zip
        asset_content_type: application/zip
